net: deepset

epochs: 20
shuffle_buffer: 64

loss: mean_absolute_error
optimizer: adam
lr: 1.e-3

callbacks:
  min_delta: 1.e-4
  patience: 5
  factor: 0.2
  min_lr: 1.e-6

model:
  deepset:
    type: resnet # mlp or resnet
    activation: relu
    initializer: he_normal
    dropout: 0.2
    units: [100, 50, 100, 50]

  particlenet:
    activation: relu
    initializer: he_normal
    batch_norm: True
    pooling: average # average or max
    num_points: 100
    K: 16
    channels: [
      [64, 64, 64],
      [128, 128, 128],
      [256, 256, 256],
    ]
    dropout: 0.1
    units: [256]

data:
  batch_size: 32
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2

  num_points: 100 # ParticleNet point cutoff
  
  features:
    jets: 
      numerical: [
        pt, eta, mass, phi, area, qgl_axis2, qgl_ptD, qgl_mult
      ]
      categorical: {
        puId: [0, 4, 6, 7], partonFlavour: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 21]
      }
    pf_cands: 
      numerical: [
        pt, eta, mass, phi, d0, d0Err, dz, dzErr, puppiWeight, puppiWeightNoLep, trkChi2, vtxChi2
      ]
      categorical: {
        charge: [-1, 0, 1], lostInnerHits: [-1, 0, 1, 2], 
        pdgId: [-211, -13, -11, 1, 2, 11, 13, 22, 130, 211], 
        pvAssocQuality: [0, 1, 4, 5, 6, 7], trkQuality: [0, 1, 5]
      }
      synthetic: [
        rel_pt, rel_eta, rel_mass, rel_phi
      ]