indir: sample
outdir: sample

epochs: 10

callbacks:
  min_delta: 1.e-4
  patience: 5
  factor: 0.5
  min_lr: 1.e-6

model:
  layers: [100, 100, 100]
  activation: relu
  initializer: he_uniform

data:
  batch_size: 42
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2
  
  features:
    jets: [
      Jet_pt, Jet_genJetIdx, Jet_area, Jet_eta, Jet_mass, Jet_phi, Jet_muEF,
      Jet_hfEmEF, Jet_hfHEF, Jet_chEmEF, Jet_chHEF, Jet_neEmEF, Jet_neHEF
    ]
    gen_jets: [
      GenJet_pt, GenJet_eta, GenJet_partonFlavour, GenJet_hadronFlavour
    ]
    jet_pf_cands: [
      JetPFCands_pt, JetPFCands_jetIdx, JetPFCands_pFCandsIdx, 
      JetPFCands_btagEtaRel, JetPFCands_btagJetDistVal, JetPFCands_btagPParRatio,
      JetPFCands_btagPtRatio, JetPFCands_btagSip3dSig, JetPFCands_btagSip3dVal
    ]
    pf_cands: [
      PFCands_charge, PFCands_d0, PFCands_d0Err, PFCands_dz, 
      PFCands_dzErr, PFCands_eta, PFCands_lostInnerHits, PFCands_mass, 
      PFCands_pdgId, PFCands_phi, PFCands_pt, PFCands_puppiWeight,
      PFCands_puppiWeightNoLep, PFCands_pvAssocQuality, PFCands_trkChi2, 
      PFCands_trkQuality, PFCands_vtxChi2
    ]