epochs: 5
optimizer: adam
loss: mean_absolute_error

callbacks:
  min_delta: 1.e-4
  patience: 5
  factor: 0.5
  min_lr: 1.e-6

model:
  layers: [100, 100, 100]
  activation: relu
  initializer: he_uniform
  dropout: 0.1

data:
  batch_size: 400
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2
  
  features:
    jets: 
      numerical: [
        pt, eta #, mass, phi, area, qgl_axis2, qgl_ptD
      ]
      categorical: [
        qgl_mult
      ]
    pf_cands: 
      numerical: [
        pt, eta #, mass, phi, d0, d0Err, dz, dzErr, puppiWeight, puppiWeightNoLep, trkChi2, vtxChi2
      ]
      categorical: [
        charge, lostInnerHits, pdgId, pvAssocQuality, trkQuality
      ]