epochs: 20
optimizer: adam
loss: mean_absolute_error

callbacks:
  min_delta: 1.e-4
  patience: 5
  factor: 0.5
  min_lr: 1.e-6

model:
  layers: [100, 100, 100]
  activation: relu
  initializer: he_uniform
  dropout: 0.1

data:
  batch_size: 400
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2
  
  features:
    jets: 
      numerical: [
        pt, eta, mass, phi, area, qgl_axis2, qgl_ptD
      ]
      categorical: {
        puId: [0, 4, 6, 7]
      }
    pf_cands: 
      numerical: [
        pt, eta, mass, phi, d0, d0Err, dz, dzErr, puppiWeight, puppiWeightNoLep, trkChi2, vtxChi2
      ]
      categorical: {
        charge: [-1, 0, 1], lostInnerHits: [-1, 0, 1, 2], 
        pdgId: [-211, -13, -11, 1, 2, 11, 13, 22, 130, 211], 
        pvAssocQuality: [0, 1, 4, 5, 6, 7], trkQuality: [0, 1, 5]
      }