indir: sample
outdir: sample

epochs: 5
optimizer: adam
loss: mean_absolute_error

callbacks:
  min_delta: 1.e-4
  patience: 5
  factor: 0.5
  min_lr: 1.e-6

model:
  layers: [100, 100, 100]
  activation: relu
  initializer: he_uniform
  dropout: 0.1

data:
  batch_size: 400
  train_size: 0.6
  validation_size: 0.2
  test_size: 0.2
  
  features:
    jets: [
      pt, area, eta, mass, phi, muEF,
      hfEmEF, hfHEF, chEmEF, chHEF, neEmEF, neHEF
    ]
    gen_jets: [
      pt, eta, partonFlavour, hadronFlavour
    ]
    pf_cands: [
      d0, d0Err, dz, dzErr, eta, mass, phi, pt
    ]